
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BanckWS", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8787/?wsdl")
public class BanckWS
    extends Service
{

    private static final URL BANCKWS_WSDL_LOCATION;
    private static final WebServiceException BANCKWS_EXCEPTION;
    private static final QName BANCKWS_QNAME = new QName("http://ws/", "BanckWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8787/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANCKWS_WSDL_LOCATION = url;
        BANCKWS_EXCEPTION = e;
    }

    public BanckWS() {
        super(__getWsdlLocation(), BANCKWS_QNAME);
    }

    public BanckWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANCKWS_QNAME, features);
    }

    public BanckWS(URL wsdlLocation) {
        super(wsdlLocation, BANCKWS_QNAME);
    }

    public BanckWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANCKWS_QNAME, features);
    }

    public BanckWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BanckWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanckService
     */
    @WebEndpoint(name = "BanckServicePort")
    public BanckService getBanckServicePort() {
        return super.getPort(new QName("http://ws/", "BanckServicePort"), BanckService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanckService
     */
    @WebEndpoint(name = "BanckServicePort")
    public BanckService getBanckServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "BanckServicePort"), BanckService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANCKWS_EXCEPTION!= null) {
            throw BANCKWS_EXCEPTION;
        }
        return BANCKWS_WSDL_LOCATION;
    }

}
